modLoader = "javafml"
loaderVersion = "[0,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "crashexploitfixer"
version = "${version}"
displayName = "CrashExploitFixer"
authors = "Drex"
description = '''
A port of Papers Improve-tag-parser-handling patch, to fix a server crash exploit.
'''
#logoFile = ""