modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "crashexploitfixer"
version = "${version}"
displayName = "CrashExploitFixer"
authors = "Drex"
description = '''
A port of Papers Improve-tag-parser-handling patch, to fix a server crash exploit.
'''
#logoFile = ""

[[dependencies.crashexploitfixer]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crashexploitfixer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
