modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "crashexploitfixer"
version = "${version}"
displayName = "CrashExploitFixer"
authors = "Drex"
description = '''
A port of Papers Improve-tag-parser-handling patch, to fix a server crash exploit.
'''
#logoFile = ""

[[dependencies.crashexploitfixer]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crashexploitfixer]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "crashexploitfixer.mixins.json"
