modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "crashexploitfixer"
version = "${version}"
displayName = "CrashExploitFixer"
authors = "Drex"
description = '''
A port of Papers Improve-tag-parser-handling patch, to fix a server crash exploit.
'''
#logoFile = ""

[[dependencies.crashexploitfixer]]
modId = "neoforge"
type = "required"
versionRange = "[20.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "crashexploitfixer.mixins.json"
